services:
  ${COURSE_SUBDOMAIN}-grader:
    build: .
    container_name: bytegrader-${COURSE_SUBDOMAIN}

    # Entrypoint hack to change permissions of the volume mount
    command: >
      sh -c "
        chown -R 1000:988 /workspace &&
        chmod -R 755 /workspace &&
        exec ./bytegrader-api
      "
    
    ports:
      - "127.0.0.1:8080:8080"
      
    volumes:
      - ./uploads:/tmp/uploads
      - ./logs:/app/logs
      - /var/run/docker.sock:/var/run/docker.sock
      - ./graders/registry.yaml:/usr/local/bin/graders/registry.yaml:ro
      - bytegrader-workspace:/workspace

    user: "${DOCKER_USER_ID}:${DOCKER_GROUP_ID}"
    
    environment:
      # Course-specific settings
      - PORT=8080
      - COURSE_ID=${COURSE_SUBDOMAIN}
      - MAX_FILE_SIZE_MB=${BYTEGRADER_MAX_FILE_SIZE_MB:-50}
      - GRADING_TIMEOUT_MIN=${BYTEGRADER_GRADING_TIMEOUT_MIN:-10}
      - MAX_CONCURRENT_JOBS=${BYTEGRADER_MAX_CONCURRENT_JOBS:-2}
      - GRADING_SCRIPTS_DIR=/usr/local/bin/graders
      - DOCKER_HOST=unix:///var/run/docker.sock
      
      # Security settings (from setup-server.sh configuration)
      - REQUIRE_API_KEY=${BYTEGRADER_REQUIRE_API_KEY:-false}
      - VALID_API_KEYS=${BYTEGRADER_VALID_API_KEYS:-}
      - ALLOWED_IPS=${BYTEGRADER_ALLOWED_IPS:-}
      
      # Rate limiting settings
      - RATE_LIMIT_ENABLED=${BYTEGRADER_RATE_LIMIT_ENABLED:-true}
      - RATE_LIMIT_REQUESTS=${BYTEGRADER_RATE_LIMIT_REQUESTS:-100}
      - RATE_LIMIT_WINDOW_MIN=${BYTEGRADER_RATE_LIMIT_WINDOW_MIN:-5}
      
      # Cleanup settings
      - CLEANUP_INTERVAL_HOURS=${BYTEGRADER_CLEANUP_INTERVAL_HOURS:-1}
      - COMPLETED_JOB_TTL_HOURS=${BYTEGRADER_COMPLETED_JOB_TTL_HOURS:-24}
      - FAILED_JOB_TTL_HOURS=${BYTEGRADER_FAILED_JOB_TTL_HOURS:-24}
      - OLD_FILE_TTL_HOURS=${BYTEGRADER_OLD_FILE_TTL_HOURS:-48}
    
    restart: unless-stopped
    
    security_opt:
      - no-new-privileges:true
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 800M
          cpus: '1.0'
        reservations:
          memory: 400M
          cpus: '0.3'

volumes:
  bytegrader-workspace:
    external: true
    name: bytegrader-workspace
